{% set name = "constyle" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 842009155b6629eb7b40f32c6fff7b79853109f79f2a9d1821b8808b9c7e188c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - constyle = constyle.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - importlib-metadata >=4.11.0,<5.0.0a
    - attributes-doc >=0.3.0

test:
  imports:
    - constyle
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/abrahammurciano/python-constyle
  summary: A Python library to add style to your console
  description: |
    A Python library to add style to your console.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://abrahammurciano.github.io/python-constyle/constyle
  dev_url: https://github.com/abrahammurciano/python-constyle

extra:
  recipe-maintainers:
    - abrahammurciano
